[tool]
id = "mi-module-gen"

[[dependency]]
path = "../tool-mi-module-gen-cli/build/libs/tool-mi-module-gen-cli-0.3.0-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/tool-compiler-plugin-0.3.0-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/antlr4-runtime-4.5.1-1.jar"

[[dependency]]
path = "../compiler-plugin/build/handlebars-4.0.6.jar"
